import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"
    className={`${outfit.variable} h-full antialiased`}>
    <ClerkProvider>
    <body className="min-h-full flex flex-col font-sans">{children}</body>
    </ClerkProvider>
    </html>
  );
  }